/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReviewAll;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FrmJList extends javax.swing.JFrame {

    /**
     * Creates new form FrmJList
     */
    public FrmJList() {
        initComponents();
        JList.setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSoChan = new javax.swing.JButton();
        btnSoLe = new javax.swing.JButton();
        btnSoNT = new javax.swing.JButton();
        btnBoDen = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNhap = new javax.swing.JButton();
        txtNhap = new javax.swing.JTextField();
        CboxSoAm = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        JList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thao tác trên JList");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Thao tác trên JList - Checkbox");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnSoChan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSoChan.setText("Tô đen số chẵn");
        btnSoChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoChanActionPerformed(evt);
            }
        });

        btnSoLe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSoLe.setText("Tô đen số lẻ");
        btnSoLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoLeActionPerformed(evt);
            }
        });

        btnSoNT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSoNT.setText("Tô đen số nguyên tố");
        btnSoNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoNTActionPerformed(evt);
            }
        });

        btnBoDen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBoDen.setText("Bỏ tô đen");
        btnBoDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoDenActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnXoa.setText("Xóa các giá trị đang tô đen");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTong.setText("Tổng giá trị trong JList");
        btnTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSoChan)
                    .addComponent(btnSoLe)
                    .addComponent(btnSoNT)
                    .addComponent(btnBoDen)
                    .addComponent(btnXoa)
                    .addComponent(btnTong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSoChan)
                .addGap(18, 18, 18)
                .addComponent(btnSoLe)
                .addGap(18, 18, 18)
                .addComponent(btnSoNT)
                .addGap(18, 18, 18)
                .addComponent(btnBoDen)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnTong)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnNhap.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        CboxSoAm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CboxSoAm.setText("Cho nhập số âm");

        jScrollPane1.setViewportView(JList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CboxSoAm)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhap)
                    .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxSoAm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThoat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThoat.setText("Đóng chương trình");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(btnThoat)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(btnThoat)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Thong bao", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed
    DefaultListModel list = new DefaultListModel();
    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
//        DefaultListModel list = (DefaultListModel) JList.getModel();
        try {
            int a = Integer.parseInt(txtNhap.getText());
            if (a < 0 && !CboxSoAm.isSelected()) {
                throw new Exception();
            }
            list.addElement(a);
            JList.setModel(list);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please input the positive integer ");
        }
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnSoChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoChanActionPerformed
        int indies = JList.getModel().getSize();
        for (int i = 0; i < indies; i++) {
            if (Integer.parseInt(list.getElementAt(i).toString()) % 2==0) {
                JList.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_btnSoChanActionPerformed

    private void btnSoLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoLeActionPerformed
        int indies = JList.getModel().getSize();
        for (int i = 0; i < indies; i++) {
            if (Integer.parseInt(list.getElementAt(i).toString()) % 2 == 1) {
                JList.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_btnSoLeActionPerformed

    private void btnSoNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoNTActionPerformed
        int indies = JList.getModel().getSize();
        for (int i = 0; i < indies; i++) {
            if (isPrimeNumber(Integer.parseInt(list.getElementAt(i).toString()))) {
                JList.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_btnSoNTActionPerformed

    private void btnBoDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoDenActionPerformed
        int indies = JList.getModel().getSize();
        for (int i = 0; i < indies; i++) {
            JList.removeSelectionInterval(i, indies);
        }
//        JList.clearSelection();
    }//GEN-LAST:event_btnBoDenActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(this.JList.getSelectedIndices().length > 0) {
          int[] selectedIndices = JList.getSelectedIndices();
          for (int i = selectedIndices.length-1; i >=0; i--) {
              list.removeElementAt(selectedIndices[i]);
          }
        }
        JList.setModel(list);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongActionPerformed
        int indies = JList.getModel().getSize();
        int S=0;
        for (int i = 0; i < indies; i++) {
            S=S+Integer.parseInt(list.getElementAt(i).toString());
        }
        JOptionPane.showMessageDialog(null, "Tổng giá trị trong JList = "+S);
    }//GEN-LAST:event_btnTongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJList().setVisible(true);
            }
        });
    }
    
    public static boolean isPrimeNumber(int i) {
        for (int j = 2; j < i; j++) {
            {
                if (i % j == 0) {
                    return false;
                }
            }

        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CboxSoAm;
    private javax.swing.JList<String> JList;
    private javax.swing.JButton btnBoDen;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSoChan;
    private javax.swing.JButton btnSoLe;
    private javax.swing.JButton btnSoNT;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNhap;
    // End of variables declaration//GEN-END:variables
}
